[build]
target = "thumbv6m-none-eabi"
rustflags = ["-Z", "threads=8"]
# rustc-wrapper = "/usr/local/cargo/bin/sccache"

[target.thumbv6m-none-eabi]
rustflags = [
    "-Z",
    "threads=8",
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "no-vectorize-loops",
]

runner = "elf2uf2-rs"
